title: Traelincoln on Github
description: Where I store and share my work online
theme: jekyll-theme-modernist
destination: docs
github: [metadata]
layout: default
baseurl: trevourchidoti.me
url: ""

# my custom defaults

defaults:
  - 
    scope: 
        path: ""
    values:
      my_pageclip: true


