
title: [Simplified]
description: [Simplified is a blog and owned by me, Trevour Chidoti. It's a place where I write about life, science and tech in simple terms.]

destination: docs/


theme: jekyll-theme-modernist
